name: Frontend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Restart Frontend
        run: pm2 restart bluestone-frontend
